-- MySQL Script generated by MySQL Workbench
-- Wed Sep  1 17:23:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `brandName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBrand`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idBrand_UNIQUE` ON `mydb`.`Brand` (`idBrand` ASC) VISIBLE;

CREATE UNIQUE INDEX `Brandcol_UNIQUE` ON `mydb`.`Brand` (`brandName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `colorName` VARCHAR(45) NOT NULL,
  `colorCode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idColor_UNIQUE` ON `mydb`.`Color` (`idColor` ASC) VISIBLE;

CREATE UNIQUE INDEX `nameColor_UNIQUE` ON `mydb`.`Color` (`colorName` ASC) VISIBLE;

CREATE UNIQUE INDEX `colorCode_UNIQUE` ON `mydb`.`Color` (`colorCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idPro` INT NOT NULL AUTO_INCREMENT,
  `proName` VARCHAR(100) NOT NULL,
  `proDescript` LONGTEXT NOT NULL,
  `proPrice` DECIMAL(10,2) NOT NULL,
  `proAmount` INT NOT NULL,
  `proMFD` DATE NOT NULL,
  `proPathImg` MEDIUMTEXT NOT NULL,
  `idBrand` INT NOT NULL,
  PRIMARY KEY (`idPro`, `idBrand`),
  CONSTRAINT `fk_Product_Brand`
    FOREIGN KEY (`idBrand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProduct_UNIQUE` ON `mydb`.`Product` (`idPro` ASC) VISIBLE;

CREATE UNIQUE INDEX `proName_UNIQUE` ON `mydb`.`Product` (`proName` ASC) VISIBLE;

CREATE INDEX `fk_Product_Brand_idx` ON `mydb`.`Product` (`idBrand` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ProWithColors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProWithColors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProWithColors` (
  `idProWithCol` INT NOT NULL AUTO_INCREMENT,
  `idColor` INT NOT NULL,
  `idPro` INT NOT NULL,
  PRIMARY KEY (`idProWithCol`, `idColor`, `idPro`),
  CONSTRAINT `fk_Color_has_Product_Color`
    FOREIGN KEY (`idColor`)
    REFERENCES `mydb`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Color_has_Product_Product`
    FOREIGN KEY (`idPro`)
    REFERENCES `mydb`.`Product` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Color_has_Product_Product_idx` ON `mydb`.`ProWithColors` (`idPro` ASC) VISIBLE;

CREATE INDEX `fk_Color_has_Product_Color_idx` ON `mydb`.`ProWithColors` (`idColor` ASC) VISIBLE;

CREATE UNIQUE INDEX `idProWithCol_UNIQUE` ON `mydb`.`ProWithColors` (`idProWithCol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cart` (
  `idCart` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCart`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCart_UNIQUE` ON `mydb`.`Cart` (`idCart` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `accUsername` VARCHAR(45) NULL,
  `accPass` VARCHAR(45) NULL,
  `accRole` VARCHAR(45) NOT NULL,
  `accFname` VARCHAR(45) NOT NULL,
  `accLname` VARCHAR(45) NOT NULL,
  `accPhone` VARCHAR(20) NOT NULL,
  `accAddress` VARCHAR(300) NOT NULL,
  `idCart` INT NOT NULL,
  PRIMARY KEY (`idAccount`, `idCart`),
  CONSTRAINT `fk_Account_Cart1`
    FOREIGN KEY (`idCart`)
    REFERENCES `mydb`.`Cart` (`idCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `accUsername_UNIQUE` ON `mydb`.`Account` (`accUsername` ASC) VISIBLE;

CREATE INDEX `fk_Account_Cart1_idx` ON `mydb`.`Account` (`idCart` ASC) VISIBLE;

CREATE UNIQUE INDEX `idAccount_UNIQUE` ON `mydb`.`Account` (`idAccount` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CartDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CartDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CartDetails` (
  `idCartDetail` INT NOT NULL AUTO_INCREMENT,
  `idPro` INT NOT NULL,
  `idCart` INT NOT NULL,
  `piecePerOnePro` INT NOT NULL COMMENT 'Product นึงมีกี่ชิ้น\nเสื้อ A มีจำนวน 10 ชิ้น\nเสื้อ B มีจำนวน 10 ชิ้น\nproPerPiece(A) = 10\nproPerPiece(B) = 10',
  PRIMARY KEY (`idCartDetail`, `idPro`, `idCart`),
  CONSTRAINT `fk_CartDetail_Product1`
    FOREIGN KEY (`idPro`)
    REFERENCES `mydb`.`Product` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartDetail_Cart1`
    FOREIGN KEY (`idCart`)
    REFERENCES `mydb`.`Cart` (`idCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CartDetail_Product_idx` ON `mydb`.`CartDetails` (`idPro` ASC) VISIBLE;

CREATE INDEX `fk_CartDetail_Cart_idx` ON `mydb`.`CartDetails` (`idCart` ASC) VISIBLE;

CREATE UNIQUE INDEX `idCartDetail_UNIQUE` ON `mydb`.`CartDetails` (`idCartDetail` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Receipt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Receipt` (
  `idReceipt` INT NOT NULL AUTO_INCREMENT,
  `idAccount` INT NOT NULL,
  PRIMARY KEY (`idReceipt`, `idAccount`),
  CONSTRAINT `fk_Receipt_Account1`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Receipt_Account1_idx` ON `mydb`.`Receipt` (`idAccount` ASC) VISIBLE;

CREATE UNIQUE INDEX `idReceipt_UNIQUE` ON `mydb`.`Receipt` (`idReceipt` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ReceiptDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ReceiptDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ReceiptDetails` (
  `idReceiptDetails` INT NOT NULL AUTO_INCREMENT,
  `idReceipt` INT NOT NULL,
  `idPro` INT NOT NULL,
  `proPerPiece` INT NOT NULL COMMENT 'เสื้อ A มีจำนวน 10 ชิ้น\nเสื้อ B มีจำนวน 10 ชิ้น\nproPerPiece(A) = 10\nproPerPiece(B) = 10',
  PRIMARY KEY (`idReceiptDetails`, `idReceipt`, `idPro`),
  CONSTRAINT `fk_ReceiptDetails_Receipt1`
    FOREIGN KEY (`idReceipt`)
    REFERENCES `mydb`.`Receipt` (`idReceipt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReceiptDetails_Product1`
    FOREIGN KEY (`idPro`)
    REFERENCES `mydb`.`Product` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ReceiptDetails_Receipt1_idx` ON `mydb`.`ReceiptDetails` (`idReceipt` ASC) VISIBLE;

CREATE INDEX `fk_ReceiptDetails_Product1_idx` ON `mydb`.`ReceiptDetails` (`idPro` ASC) VISIBLE;

CREATE UNIQUE INDEX `idReceiptDetails_UNIQUE` ON `mydb`.`ReceiptDetails` (`idReceiptDetails` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
